import type { Metadata } from "next";
import Link from "next/link";

import {
  PageHeader,
  PageShell,
  Section,
} from "@/app/components/ui/page-shell";

/*
 * ⚠️ STRUCTURAL PLACEHOLDER — NOT LEGAL ADVICE.
 *
 * Written to match what the app actually does, so the structure and the
 * disclaimers are honest. It has NOT been reviewed by a lawyer.
 *
 * Before launch this must be reviewed by qualified counsel and completed with:
 *   - the legal entity name and registered address
 *   - governing law and jurisdiction for disputes
 *   - final subscription terms: price, billing cycle, refund and cancellation
 *   - statutory consumer rights that cannot be excluded in your market
 *   - a limitation-of-liability clause drafted for that jurisdiction
 */

export const metadata: Metadata = {
  title: "Terms of Service — Spiritual Oracle",
  robots: { index: false, follow: true },
};

const LAST_UPDATED = "15 August 2026";
const SUPPORT_EMAIL = "hello@spiritualoracle.app";

export default function TermsPage() {
  return (
    <PageShell>
      <PageHeader
        eyebrow={`Last updated ${LAST_UPDATED}`}
        title="Terms of Service"
        lead="The agreement between you and Spiritual Oracle."
      />

      <div className="mb-10 rounded-xl border border-line-strong bg-surface-2 px-5 py-4 text-sm leading-6 text-caution">
        These terms are a working draft pending legal review. They describe our
        intended terms but are not yet a finalised legal document.
      </div>

      <Section title="Using the service">
        <p>
          You need an account to ask questions. Keep your login details to
          yourself — you are responsible for activity under your account. You
          must be old enough to form a binding contract where you live.
        </p>
      </Section>

      <Section title="Acceptable use">
        <p>
          Do not attempt to break, overload or circumvent the service, including
          its free-tier limits. Do not scrape the corpus wholesale, resell
          access, or use the service to harass anyone or to generate unlawful
          content.
        </p>
        <p>
          We may suspend accounts that do these things, and we will normally
          tell you why.
        </p>
      </Section>

      <Section title="Reflections are not authority">
        <p>
          The reflections on this site are generated by an AI language model.
          They are offered as a prompt for your own thinking and nothing more.
        </p>
        <p>
          They are <strong>not</strong> religious teaching or authoritative
          scriptural interpretation, and they do not come from any tradition,
          lineage or institution. They are{" "}
          <strong>not</strong> medical, psychological, legal or financial
          advice. If you are facing a serious decision or are in distress,
          please talk to a qualified professional or someone you trust.
        </p>
        <p>
          AI output can be wrong, and it can be strange. Use your judgement.
        </p>
      </Section>

      <Section title="The source texts">
        <p>
          The Bhagavad Gita and the Ramcharitmanas are ancient works in the
          public domain. The English translations we use are published
          translations we believe to be in the public domain, and translators
          are credited alongside every verse.
        </p>
        <p>
          The site design, code, and the reflections generated for you remain
          ours. You are free to keep, quote and share the reflections you
          personally receive.
        </p>
        <p>
          If you hold rights in any text used here and believe it has been
          included in error, contact us and we will remove it while we look into
          it.
        </p>
      </Section>

      <Section title="Subscriptions and billing">
        <p>
          A free tier is available with a limited number of questions. Paid
          plans are billed in advance for a recurring period and renew until you
          cancel. Cancelling stops future charges; access continues to the end
          of the period already paid for.
        </p>
        <p className="text-muted">
          Final prices, billing periods and refund terms are not yet set.
          Billing is not currently connected, and nothing on this site can
          charge you today. This section will be completed before launch.
        </p>
      </Section>

      <Section title="Availability and changes">
        <p>
          The service is provided as-is. We do not guarantee uninterrupted
          availability, and we may change or discontinue features. If we make a
          material change to these terms, we will update the date at the top of
          this page and, for significant changes, tell account holders directly.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Questions about these terms:{" "}
          <a
            href={`mailto:${SUPPORT_EMAIL}`}
            className="text-accent underline-offset-4 hover:underline"
          >
            {SUPPORT_EMAIL}
          </a>
          , or via the{" "}
          <Link
            href="/contact"
            className="text-accent underline-offset-4 hover:underline"
          >
            contact page
          </Link>
          .
        </p>
      </Section>
    </PageShell>
  );
}
